version: "3.2"
services:

  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: dockerfile
    image: raianedev/application_resume:1.0
    ports:
      - 80:80
      - 433:433
    env_file: ./backend/.env