version: "3.2"
services:
  server:
    container_name: server
    image: nginx:1.17.8
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./Frontend/build:/usr/share/nginx/html
      - ./Frontend/public:/usr/share/nginx/html
    command: ["nginx", "-g", "daemon off;"]

  database:
    container_name: database
    image: postgres:10.3
    env_file: ./.env
    volumes:
        - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: ./Backend
      dockerfile: ./dockerfile.back
    volumes:
      - ./:/Backend
      - app:/Backend
    env_file:
      - ./.env
    ports:
      - 8088:8088
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: ./Frontend
      dockerfile: ./dockerfile.front
    volumes:
      - ./:/Frontend
      - app:/Frontend
    env_file:
      - ./.env
    restart: on-failure


volumes:
  app:
  postgres: